'use client';

import React from 'react';
import { FileText, Download, MoreHorizontal, CheckCircle2, Loader2 } from 'lucide-react';
import { ReportLog } from '../types';

const historyData: ReportLog[] = [
  { id: '101', name: 'Inventory_Jan24.pdf', type: 'Inventory', generatedBy: 'John Doe', date: 'Jan 28, 2024', size: '2.4 MB', format: 'PDF', status: 'Ready' },
  { id: '102', name: 'Sales_Q4_2023.csv', type: 'Production', generatedBy: 'Admin', date: 'Jan 25, 2024', size: '850 KB', format: 'CSV', status: 'Ready' },
  { id: '103', name: 'Alerts_Log.xlsx', type: 'Alerts', generatedBy: 'Sarah Smith', date: 'Jan 20, 2024', size: '120 KB', format: 'Excel', status: 'Processing' },
  { id: '104', name: 'Full_Audit_Log.pdf', type: 'Activity', generatedBy: 'John Doe', date: 'Jan 15, 2024', size: '15.2 MB', format: 'PDF', status: 'Ready' },
];

export const ReportHistory = () => {
  return (
    <div className="bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden">
      <div className="px-6 py-5 border-b border-gray-100 flex justify-between items-center">
        <h3 className="font-bold text-gray-900">Recent Reports History</h3>
        <button className="text-sm text-blue-600 hover:text-blue-700 font-medium">View All</button>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="bg-gray-50/50 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
              <th className="px-6 py-4">Report Name</th>
              <th className="px-6 py-4">Type</th>
              <th className="px-6 py-4">Generated By</th>
              <th className="px-6 py-4">Date</th>
              <th className="px-6 py-4">Status</th>
              <th className="px-6 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {historyData.map((log) => (
              <tr key={log.id} className="hover:bg-gray-50/50 transition-colors">
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-gray-100 rounded-lg text-gray-500">
                      <FileText size={18} />
                    </div>
                    <div>
                      <p className="font-medium text-gray-900 text-sm">{log.name}</p>
                      <p className="text-xs text-gray-400">{log.size} • {log.format}</p>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4 text-sm text-gray-600">{log.type}</td>
                <td className="px-6 py-4 text-sm text-gray-600">{log.generatedBy}</td>
                <td className="px-6 py-4 text-sm text-gray-600">{log.date}</td>
                <td className="px-6 py-4">
                  {log.status === 'Ready' ? (
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-green-50 text-green-700">
                      <CheckCircle2 size={12} /> Ready
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-blue-50 text-blue-700">
                      <Loader2 size={12} className="animate-spin" /> Processing
                    </span>
                  )}
                </td>
                <td className="px-6 py-4 text-right">
                  <div className="flex items-center justify-end gap-2">
                    <button className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Download">
                      <Download size={18} />
                    </button>
                    <button className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors">
                      <MoreHorizontal size={18} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};